num1=str(input("Enter the produt:"))
num2=int(input("enter the quantity:"))
num3=int(input("enter the product price:"))
discount=float(input("enter the discount percentage:"))
tax=int(input("Enter th tax"))
print("product is:",num1)
print("quantity of the product:",num2)

total=(num2*num3)
print("price:",total)
discount=(total*discount/100)
print("Discount:",discount)
total_price=(total-discount)
print("totel price:", total_price)
tax=(total_price*tax/100)
